name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # https://github.com/bevyengine/bevy/blob/main/docs/linux_dependencies.md
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install libx11-dev libasound2-dev libudev-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Build
        run: cargo build --release

      - name: Test
        run: cargo test --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: opentd-linux
          path: ${{runner.workspace}}/opentd/target/release/opentd
